### ISSUE TITLE
Milestone 1 Demo

### ISSUE THREAD

**Issue by lucastliu** [lucastliu/gmailfs#11]
Full functionality for gmailfs demo with real gmail account

- [x]  Use gmailfs to see real list of inbox emails, 

- [x] Be able to read contents of specific email

- [x] After receiving a real email, gmailfs reflects this update
- [x] Can send a real email to another address
